read_file = open("D:/black/demo.txt","r",encoding="UTF-8")
print(read_file.read())
read_file.close()
append_file = open("D:/black/demo.txt","a",encoding="UTF-8")
append_file.write("hello world")
append_file.close()